name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"

    - uses: engineerd/setup-kind@v0.6.2
      with:
        version: "v0.24.0"
        image: kindest/node:v1.34.0@sha256:7416a61b42b1662ca6ca89f02028ac133a309a2a30ba309614e8ec94d976dc5a

    - name: Testing kind cluster set-up
      run: |
        set -x
        kubectl cluster-info
        kubectl get pods -n kube-system -v 10
        echo "kubectl config current-context:" "$(kubectl config current-context)"
        echo "KUBECONFIG env var:" "${KUBECONFIG}"

    - name: E2E test
      working-directory: ./e2e
      run: |
        KUBECONFIG=/home/runner/.kube/config \
        DOCKER_USERNAME=skevetter \
        DOCKER_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
        CONTAINER_REGISTRY=ghcr.io \
        go test -v -ginkgo.v -timeout 3600s
